# Generated by Django 4.0.6 on 2022-09-23 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manageuser', '0001_initial'),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=30)),
                ('message', models.TextField(max_length=200)),
                ('batch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.batch')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.course')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageuser.student_tbl')),
            ],
        ),
    ]
