# Generated by Django 4.0.6 on 2022-09-27 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manageuser', '0001_initial'),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentbatch',
            name='batch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='training.batch'),
        ),
        migrations.AlterField(
            model_name='studentbatch',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='manageuser.student_tbl'),
        ),
    ]
